export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 202,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  NOT_FOUND: 404,
  CONFLICT: 409,
  SERVER_ERROR: 500,
};

export const MONGO_DB_ERRORS = {
  DUPLICATE_KEY: 11000,
};

export const APP_CONFIG = {
  DEFAULT_ACTIVITY_COLOR: "#ffffff",
  MAX_ACTIVITY_NAME_LENGTH: 50,
  MIN_ACTIVITY_DURATION_MS: 5 * 60 * 1000, // 5 minutes
  MAX_ACTIVITY_DURATION_MS: 24 * 60 * 60 * 1000, // 24 hours
  MIN_GAP_DURATION_FOR_CONFIRMATION_MS: MIN_ACTIVITY_DURATION_MS,
  MAX_GAP_DURATION_FOR_CONFIRMATION_MS: MAX_ACTIVITY_DURATION_MS,
  NO_TIMER_RECOVERY_BEYOND_THIS_MS: MAX_GAP_DURATION_FOR_CONFIRMATION_MS,
};
